masteral/master_app/urls.py
from django.urls import path
from . import views
from django.conf.urls import static
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from django.urls import include, re_path
app_name = 'activities'

urlpatterns = [
    path('', views.pcg, name='pcg'),
    path('list', views.list, name='list'),
    path('profile', views.profile, name='profile'),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masteral/masteral/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('master_app.urls')),
    
    
    # path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'))
]

masteral/master_app/models.py
from django.db import models

# Create your models here.

masteral/master_app/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect,  reverse

# Create your views here.
def pcg(request):
    return render(request, 'activities/index.html')

def list(request):
    return render (request, 'activities/breakdown.html')

def profile(request):
    return render(request, 'activities/profile.html')

masteral/master_app/templates/activities/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="../../static/css/index.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COAST GUARD</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="../../static/img/pcg.png" id="aims" alt="Aims logo" width="30" height="24">
            </a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#part2">ABOUT</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link " href="/profile">RESEACRHER'S PROFILE</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link " href="/list">RESEARCH CHAPTERS</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Disabled</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>

    <div class="outside">
        <div class="part1">
            <!-- <br>
            <br>
            <h1 id="title">AN EVALUATION OF THE PHILIPPINE COAST GUARD COMPREHENSIVESTRATEGY ON MARITIME SECURITY: TOWARDS AN ENHANCED MARITIME SECURITY PLAN IN THE WEST PHILIPPINE SEA</h1>
            <br>
            <br>
            <br> -->
            <!-- <p style="text-align: center; font-weight:bold;">A Thesis<br>Presented to the Faculty of School of Graduate Studies<br>Asian Institute of Maritime Studies<br>Pasay City</p> -->
            <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="5000">
                        <img src="../../static/img/cropped_image (1).png" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <!-- <h5>First slide label</h5>
                            <p>Some representative placeholder content for the first slide.</p> -->
                        </div>
                    </div>
                    <!-- <div class="carousel-item" data-bs-interval="5000">
                        <img src="../../static/img/cropped_image (1).png" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Second slide label</h5>
                            <p>Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="../../static/img/cropped_image (1).png" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Third slide label</h5>
                            <p>Some representative placeholder content for the third slide.</p>
                        </div>
                    </div> -->
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <br>
        <p style="text-align: center; font-weight:bold;">A Thesis<br>Presented to the Faculty of School of Graduate Studies<br>Asian Institute of Maritime Studies<br>Pasay City</p>
    </div>
    <div class="part2" id="part2">
        <br>
        <!-- <p style="text-align: center; font-size:30px;">(Title)</p> -->
        <h2 class="title2">" AN EVALUATION OF THE PHILIPPINE COAST GUARD COMPREHENSIVE STRATEGY ON MARITIME SECURITY: TOWARDS AN ENHANCED MARITIME SECURITY PLAN IN THE WEST PHILIPPINE SEA"
        </h2>
        <br>
        <br>
        <br>
        <div class="profile">
            <img src="../../static/img/LT MONTEMAR PCG(Grad Picture for Staff Course).jpg" alt="">
        </div>
        <br>
        <h3 style="text-align: center;">Ramil E. Montemar</h3>
        <p style="text-align: center; font-weight:bold;">( Researcher )</p>


        <!-- <h3 style="text-align: center;">2022 - 2023</h3> -->


    </div>
    <br>

    <div class="part3">
        <br>
        <br>
        <h2 style="text-align: center; font-weight:bold;">Abstract</h2>
        <p id="abstract" align="justify">
            &nbsp;&nbsp;&nbsp;&nbsp;This research endeavor is centered around a comprehensive examination and assessment of a strategic framework aimed at bolstering efficient maritime security. The investigation is carried out by delving into the perspectives held
            by respondents on pivotal metrics that encompass national security, ecological wellbeing, the utilization of finite energy resources, and safeguarding physical integrity. To achieve this, the study methodically gathered pertinent data, encompassing
            various dimensions of the respondents' profiles, including but not limited to gender, age, the pinnacle of educational accomplishment, and the duration of their service. The intent behind this data collection was to gain a nuanced understanding
            of the diverse demographic makeup of those participating in the study. The outcomes of this rigorous investigation unveiled a predominantly affirmative assessment of the comprehensive strategy, signifying its efficacy in adeptly addressing
            a spectrum of security apprehensions. However, these positive evaluations were not evenly distributed across all subgroups. Notable disparities surfaced in the evaluations, particularly in relation to age brackets and educational achievements.
            Drawing on these outcomes, several actionable recommendations can be delineated. Firstly, it is advised that the strategy be tailored to cater to the distinctive needs and viewpoints of varying age clusters. This responsive approach acknowledges
            the different generational perspectives on security matters and aligns the strategy more closely with the values and concerns of each age group. Furthermore, the need for enhanced collaboration among different governmental bodies and agencies
            becomes evident. By fostering greater inter-agency coordination, the strategy's implementation can be streamlined, ensuring a more cohesive and efficient approach to maritime security management. The findings also emphasize the significance
            of incorporating sustainability principles and community participation into the strategy. Recognizing the interdependence between environmental conservation and maritime security, the strategy can be refined to encompass eco-friendly practices,
            thereby fortifying natural security. Moreover, community engagement can create a network of vigilant stakeholders who actively contribute to the safety and well-being of maritime domains. In sum, these insightful findings hold substantial
            implications for the strategic evolution of maritime security policies and initiatives. The research not only underscores the overarching success of the existing strategy but also elucidates avenues for further enhancement. By embracing the
            suggested recommendations and accommodating the diverse viewpoints of various demographics, stakeholders can bolster the resilience and effectiveness of maritime security measures in a rapidly evolving global landscape. Keywords: comprehensive
            strategy, maritime security, evaluation, demographic analysis, national security, natural security, non-renewable energy, physical security.
        </p>

    </div>
    <form action="{% url 'activities:list'%}">
        {% csrf_token %}
        <div class="part4">

            <button style="margin: auto !important;" type="submit" class="btn btn-lg btn-primary">Read More >>></button>

        </div>
    </form>
    <br>
    <br>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

masteral/master_app/templates/activities/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COAST GUARD</title>
    <link rel="stylesheet" href="../../static/css/profile.css">

    <script src="https://kit.fontawesome.com/51e2c1efc6.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="../../static/img/pcg.png" id="aims" alt="Aims logo" width="30" height="24">
            </a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="/">HOME</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link active" href="/profile">RESEACRHER'S PROFILE</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link " href="/list">RESEARCH CHAPTERS</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link active" href="#" tabindex="-1">Disabled</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>
    <br>

    <header>
        <h1>Researcher's Profile</h1>
        <div class="profile-pic">
            <img src="../../static/img/LT MONTEMAR PCG(Grad Picture for Staff Course).jpg" alt="Profile Picture">
        </div>
    </header>

    <main>
        <section class="about-me">
            <h2>About Me</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget risus sed lorem mollis laoreet.</p>
        </section>

        <section class="contact-info">
            <h2>Contact Information</h2>
            <ul>
                <li>Email: example@example.com</li>
                <li>Phone: +1 123-456-7890</li>
                <li>Website: <a href="https://www.example.com">www.example.com</a></li>
            </ul>
        </section>
    </main>

    <footer>
        <p>&copy; 2023 My Profile</p>
    </footer>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>